# -*- coding: utf-8 -*-
"""cv3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xElxc1DTU6DeOXNS4a2GVVkef2uTIis1
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def show_comparison(original, blur3, blur5, blur7):
    plt.figure(figsize=(12, 10))

    # Original Image
    plt.subplot(2, 2, 1)
    plt.imshow(original, cmap='gray')
    plt.title("Original Grayscale Image")
    plt.axis('off')

    # 3x3 Kernel
    plt.subplot(2, 2, 2)
    plt.imshow(blur3, cmap='gray')
    plt.title("Average Filter (3x3)")
    plt.axis('off')

    # 5x5 Kernel
    plt.subplot(2, 2, 3)
    plt.imshow(blur5, cmap='gray')
    plt.title("Average Filter (5x5)")
    plt.axis('off')

    # 7x7 Kernel
    plt.subplot(2, 2, 4)
    plt.imshow(blur7, cmap='gray')
    plt.title("Average Filter (7x7)")
    plt.axis('off')

    plt.tight_layout()
    plt.show()

# 1. Read the image in gray scale
# Replace 'input_image.jpg' with your filename
img = cv2.imread('img.jpg', 0)

if img is None:
    print("Error: Image not found.")
else:
    # 2. Define averaging kernels of different sizes (3x3, 5x5, 7x7)
    # A kernel is a matrix of ones normalized by the number of elements
    kernel_3x3 = np.ones((3, 3), np.float32) / 9
    kernel_5x5 = np.ones((5, 5), np.float32) / 25
    kernel_7x7 = np.ones((7, 7), np.float32) / 49

    # 3. Apply each kernel to the image using 2D convolution
    # cv2.filter2D performs the convolution operation
    blur_3x3 = cv2.filter2D(img, -1, kernel_3x3)
    blur_5x5 = cv2.filter2D(img, -1, kernel_5x5)
    blur_7x7 = cv2.filter2D(img, -1, kernel_7x7)

    # 4. Display the original and blurred images for comparison
    show_comparison(img, blur_3x3, blur_5x5, blur_7x7)